### ISSUE TITLE
Working with WP_Query

### ISSUE THREAD

**Issue by JPry** [burbswp/main-presentations#11]
Alternate title: Make `WP_Query` great again.

This could be a talk about how to work with custom queries in WordPress using `WP_Query`. It would also include methods to optimize your use of advanced queries to make sure you're not slowing down your site.

This is one I'd be willing to volunteer to give.

**Comment by MattRyanCo** [comment]
ah ... that alternate title has political overtones .. but I do like the topic

**Comment by JPry** [comment]
I was thinking this could cover a few aspects of `WP_Query`:
* Why you might want to create your own custom queries with `WP_Query`
* How to work correctly with `WP_Query`
* Common mistakes, or pitfalls to avoid
* How to correctly cache queries

If anyone has input for any specific kinds of queries to cover, I could also do that too.

**Comment by lepittenger** [comment]
I could use this right now. Ha! 😄

**Comment by MattRyanCo** [comment]
I could use this too....._

**Comment by JPry** [comment]
@lepittenger @MattRy @liamdempsey 

Since this topic will be covered at next month's meet up, now is the time to send specific questions my way if you want me to include them in the presentation :)

**Comment by MattRyanCo** [comment]
Hi @JPry - Here's a couple:
- I've used copy & paste code snippets that included query resets after the custom query was performed. I did not fully investigate why this was needed. Why is this needed? When is it needed? 
- Do custom queries add any type of performance hit to the page load time? Do I need to limit how much data is returned? Is it better to return as much as possible and then parse it in memory?

**Comment by lepittenger** [comment]
When does it make sense to use a custom query vs. manipulating the main query loop with pre_get_posts() and using the template hierarchy?

**Comment by jasonrmatson1** [comment]
I'm not sure if it's the right forum or not, but I'm interested in using elastic search or other search methodologies and I believe manipulation of this function is part of that process. Not sure though. But a discussion about search in general as well and what the options are at a high-level might be helpful to frame the rest of the discussion.

**Comment by kimwhite** [comment]
Will you be posting the slides?
(thanks for the talk, it's really challenged me to dig in a little deeper and clean up my queries.)

**Comment by JPry** [comment]
@kimwhite The slides are here: http://gh.jpry.com/presentations/working-with-wp-query/

@jasonrmatson1 To address your comment more directly, custom search solutions typically use `pre_get_posts` to intercept the query and use custom functionality to determine which posts are retrieved.

**Comment by jasonrmatson1** [comment]
yup. I was looking at this solution earlier in the day.

https://github.com/10up/ElasticPress


*Jason Matson*
*CEO, Matson Consulting Group*

*Tel: 267-323-1134 <267-323-1134> | Cell: 401-447-3966 <401-447-3966>*

*Email: jason@matsongroup.com <jason@matsongroup.com>*
*Matsongroup.com <http://matsongroup.com/>*

**Comment by JPry** [comment]
Meetup link: https://www.meetup.com/philly-burbs-wordpress-meetup/events/239871135/
