### ISSUE TITLE
Local Development AGAIN - Local-By-Flywheel

### ISSUE THREAD

**Issue by MattRyanCo** [burbswp/main-presentations#14]
Pitching an idea. 

We had a "Help Me Build My WordPress Website" - night at the Reading WP meetup last week. They were using the "[Local by Flywheel](https://local.getflywheel.com/)" tool, formerly Pressmatic, as the basis for shadowers to help the NKOTB. 

We didn't have any type of intro into the tool, so everyone had to pick it up on the fly. 

I'm thinking, not another dev environment to deal with, but I installed it and I worked with another guy to help him build his first site. He was working on Windows so we teamed up, since everyone else had their hands on the red fruity koolaid brand hardware. 

Local-by-flywheel was smooth, and ran the site fast. 

It creates containers, different from VMs, (sorry Jeremy - no vagrants here) but more portable than a WAMP/MAMP/XAMPP/DesktopServer environment. 

I like it. Any version of PHP. Select NGINX or APACHE as the server. Windows and Mac. 

 [Nice intro:](https://themeisle.com/blog/local-by-flywheel-wordpress-on-mac/)

​Good topic for a quick 5 minute spin around the room, or even a longer chat. 

And did I say it's FREE!

H​appy to do either one at an upcoming gathering of our fine group.

**Comment by JPry** [comment]
@MattRy I've actually tried out Local by Flywheel, and it does seem to be pretty nice. I didn't keep using it because I already had a bunch of projects in Vagrant set up and ready to use, but I would still recommend it as an alternative to VVV.

**Comment by MattRyanCo** [comment]
We can probably close this one out, since it has been addressed, right @liamdempsey ?
