### ISSUE TITLE
Sanitization

### ISSUE THREAD

**Issue by pbrocks** [burbswp/main-presentations#5]
[Explicit Sanitization, Validation, and Escaping](https://burbswp.slack.com/files/pbarth/F1V8HH95K/Explicit_Sanitization__Validation__and_Escaping)

**Comment by salcode** [comment]
+1

**Comment by MattRyanCo** [comment]
+1 ... bump ... whatever

**Comment by liamdempsey** [comment]
So, @palibaacsi, we have two +1 and three thumbs-ups, so let's schedule this for November. Would you be up for putting together our main talk next month?

**Comment by pbrocks** [comment]
OK, so Sanitization is the topic. Not multisite, right @liamdempsey?

**Comment by liamdempsey** [comment]
Yep, that's correct. There was a lot more interest for this topic - sanitization - than for multisite. Thanks!

**Comment by liamdempsey** [comment]
As Paul covered this in November 2016, I'm going to close this issue.

Thanks for your hard work, @pbrocks!
